{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama-local-serve.ollama.fullname" . }}
  labels:
    {{- include "ollama-local-serve.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ollama-local-serve.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- end }}
