apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ollama-local-serve.fullname" . }}-secrets
  labels:
    {{- include "ollama-local-serve.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.clickhouse.enabled }}
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhousePassword | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
